<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import I18nManager from '@/i18n/manager'
import { useQuizSession } from '@/composables/useQuizSession'
const { t } = useI18n(); const router = useRouter(); const { session } = useQuizSession(); const step = ref(0)
const steps = computed(() => [0, 1, 2].map((index) => t(`generation.steps[${index}]`))); let interval
onMounted(() => { interval = setInterval(() => { if (step.value < 2) step.value++; else { clearInterval(interval); router.push(I18nManager.i18nRoute({ name: 'perguntas' })) } }, 1150) })
onUnmounted(() => clearInterval(interval))
</script>
<template><main class="loading-page"><section><div class="growing" aria-hidden="true"><span>✦</span></div><p class="eyebrow">{{ t('generation.eyebrow') }}</p><h1>{{ t('generation.title') }}</h1><p class="file">⌑ {{ session.selectedFile || t('generation.defaultFile') }}</p><div class="progress"><div :style="{ width: `${(step + 1) / 3 * 100}%` }"></div></div><ol><li v-for="(item,index) in steps" :key="item" :class="{ active: index === step, complete: index < step }"><i>{{ index < step ? '✓' : index + 1 }}</i>{{ item }}</li></ol><p class="note">{{ t('generation.note') }}</p></section></main></template>
<style>
.loading-page { min-height: calc(100vh - 76px); display: grid; place-items: center; padding: 2rem; }.loading-page section { width: min(500px,100%); padding: 2.6rem; border: 1px solid #D8E7DC; border-radius: 25px; background: #fff; text-align: center; }.growing { width: 94px; height: 94px; margin: 0 auto 1.5rem; display: grid; place-items: center; border-radius: 50% 50% 42% 58%; color: #fff; background: #1F5B45; font-size: 2rem; animation: grow 1.4s infinite alternate; }.eyebrow { color: #347158; font-size: .72rem; font-weight: 800; letter-spacing: .1em; }.loading-page h1 { margin: .7rem 0; color: #1F5B45; font: 700 2rem Lora,serif; }.file,.note { color: #52705D; font-size: .9rem; }.file { margin: 1.2rem 0 1.5rem; }.progress { height: 8px; overflow: hidden; border-radius: 99px; background: #E7F3EA; }.progress div { height: 100%; border-radius: inherit; background: #347158; transition: width .5s; }.loading-page ol { margin: 1.6rem 0; padding: 0; display: grid; gap: .9rem; list-style: none; text-align: left; }.loading-page li { display: flex; align-items: center; gap: .7rem; color: #8AA996; font-weight: 700; }.loading-page li.active { color: #1F5B45; }.loading-page li.complete { color: #347158; }.loading-page li i { width: 25px; height: 25px; display: grid; place-items: center; border-radius: 50%; color: #fff; background: #C1DCC9; font-size: .75rem; font-style: normal; }.loading-page li.active i,.loading-page li.complete i { background: #347158; }.dark .loading-page section { border-color: #29503B; background: #18382B; }.dark .loading-page h1 { color: #BEE0C9; }.dark .file,.dark .note { color: #B8D4C1; }@keyframes grow { to { transform: rotate(8deg) scale(1.07); border-radius: 58% 42% 55% 45%; } }
</style>
